from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 592)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IconPNG/Image/IcoPNG.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 270, 881, 271))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(10, 230, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ClearButton.setFont(font)
        self.ClearButton.setObjectName("ClearButton")
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(180, 230, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.WorkGBox = QtWidgets.QGroupBox(self.centralwidget)
        self.WorkGBox.setGeometry(QtCore.QRect(250, 0, 261, 171))
        self.WorkGBox.setObjectName("WorkGBox")
        self.PingRButton = QtWidgets.QRadioButton(self.WorkGBox)
        self.PingRButton.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.PingRButton.setChecked(True)
        self.PingRButton.setObjectName("PingRButton")
        self.PortCheckerRButton = QtWidgets.QRadioButton(self.WorkGBox)
        self.PortCheckerRButton.setGeometry(QtCore.QRect(10, 40, 201, 20))
        self.PortCheckerRButton.setObjectName("PortCheckerRButton")
        self.DNSLookUpRButton = QtWidgets.QRadioButton(self.WorkGBox)
        self.DNSLookUpRButton.setGeometry(QtCore.QRect(10, 60, 95, 20))
        self.DNSLookUpRButton.setObjectName("DNSLookUpRButton")
        self.GeoIPLookUpRButton = QtWidgets.QRadioButton(self.WorkGBox)
        self.GeoIPLookUpRButton.setGeometry(QtCore.QRect(10, 80, 111, 20))
        self.GeoIPLookUpRButton.setObjectName("GeoIPLookUpRButton")
        self.DoButton = QtWidgets.QPushButton(self.WorkGBox)
        self.DoButton.setGeometry(QtCore.QRect(10, 130, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DoButton.setFont(font)
        self.DoButton.setObjectName("DoButton")
        self.NetworkLoadRButton = QtWidgets.QRadioButton(self.WorkGBox)
        self.NetworkLoadRButton.setGeometry(QtCore.QRect(10, 100, 141, 20))
        self.NetworkLoadRButton.setObjectName("NetworkLoadRButton")
        self.MainSettingsGBox = QtWidgets.QGroupBox(self.centralwidget)
        self.MainSettingsGBox.setGeometry(QtCore.QRect(10, 0, 231, 171))
        self.MainSettingsGBox.setObjectName("MainSettingsGBox")
        self.URILabel = QtWidgets.QLabel(self.MainSettingsGBox)
        self.URILabel.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.URILabel.setObjectName("URILabel")
        self.PortLine = QtWidgets.QLineEdit(self.MainSettingsGBox)
        self.PortLine.setGeometry(QtCore.QRect(160, 80, 61, 22))
        self.PortLine.setMaxLength(5)
        self.PortLine.setObjectName("PortLine")
        self.PortLabel = QtWidgets.QLabel(self.MainSettingsGBox)
        self.PortLabel.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.PortLabel.setObjectName("PortLabel")
        self.IpLabel = QtWidgets.QLabel(self.MainSettingsGBox)
        self.IpLabel.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.IpLabel.setObjectName("IpLabel")
        self.IpLine = QtWidgets.QLineEdit(self.MainSettingsGBox)
        self.IpLine.setGeometry(QtCore.QRect(110, 20, 113, 22))
        self.IpLine.setFrame(True)
        self.IpLine.setAlignment(QtCore.Qt.AlignCenter)
        self.IpLine.setObjectName("IpLine")
        self.CountLabel = QtWidgets.QLabel(self.MainSettingsGBox)
        self.CountLabel.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.CountLabel.setObjectName("CountLabel")
        self.TimeoutLabel = QtWidgets.QLabel(self.MainSettingsGBox)
        self.TimeoutLabel.setGeometry(QtCore.QRect(10, 140, 111, 16))
        self.TimeoutLabel.setObjectName("TimeoutLabel")
        self.URILine = QtWidgets.QLineEdit(self.MainSettingsGBox)
        self.URILine.setGeometry(QtCore.QRect(110, 50, 113, 22))
        self.URILine.setInputMask("")
        self.URILine.setFrame(True)
        self.URILine.setAlignment(QtCore.Qt.AlignCenter)
        self.URILine.setObjectName("URILine")
        self.TimeoutLine = QtWidgets.QLineEdit(self.MainSettingsGBox)
        self.TimeoutLine.setGeometry(QtCore.QRect(160, 140, 61, 22))
        self.TimeoutLine.setObjectName("TimeoutLine")
        self.CountLine = QtWidgets.QLineEdit(self.MainSettingsGBox)
        self.CountLine.setGeometry(QtCore.QRect(160, 110, 61, 22))
        self.CountLine.setMaxLength(4)
        self.CountLine.setObjectName("CountLine")
        self.ServerSettingsGBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ServerSettingsGBox.setGeometry(QtCore.QRect(520, 0, 371, 121))
        self.ServerSettingsGBox.setObjectName("ServerSettingsGBox")
        self.Ip2Label = QtWidgets.QLabel(self.ServerSettingsGBox)
        self.Ip2Label.setGeometry(QtCore.QRect(10, 20, 55, 16))
        self.Ip2Label.setObjectName("Ip2Label")
        self.Ip2Line = QtWidgets.QLineEdit(self.ServerSettingsGBox)
        self.Ip2Line.setGeometry(QtCore.QRect(250, 20, 113, 22))
        self.Ip2Line.setFrame(True)
        self.Ip2Line.setAlignment(QtCore.Qt.AlignCenter)
        self.Ip2Line.setObjectName("Ip2Line")
        self.Port2Label = QtWidgets.QLabel(self.ServerSettingsGBox)
        self.Port2Label.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.Port2Label.setObjectName("Port2Label")
        self.Port2Line = QtWidgets.QLineEdit(self.ServerSettingsGBox)
        self.Port2Line.setGeometry(QtCore.QRect(300, 50, 61, 22))
        self.Port2Line.setMaxLength(5)
        self.Port2Line.setObjectName("Port2Line")
        self.StartButton = QtWidgets.QPushButton(self.ServerSettingsGBox)
        self.StartButton.setGeometry(QtCore.QRect(140, 80, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.progressBar = QtWidgets.QProgressBar(self.ServerSettingsGBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 90, 61, 23))
        self.progressBar.setMaximum(1)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.ServerSettingsGBox)
        self.label.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.label.setObjectName("label")
        self.onlinelabel = QtWidgets.QLabel(self.ServerSettingsGBox)
        self.onlinelabel.setGeometry(QtCore.QRect(40, 90, 71, 16))
        self.onlinelabel.setObjectName("onlinelabel")
        self.StopButton = QtWidgets.QPushButton(self.ServerSettingsGBox)
        self.StopButton.setEnabled(False)
        self.StopButton.setGeometry(QtCore.QRect(230, 80, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.InfoTextBox = QtWidgets.QTextEdit(self.centralwidget)
        self.InfoTextBox.setGeometry(QtCore.QRect(520, 130, 371, 131))
        self.InfoTextBox.setReadOnly(True)
        self.InfoTextBox.setObjectName("InfoTextBox")
        self.WorkGBox.raise_()
        self.tableWidget.raise_()
        self.ClearButton.raise_()
        self.SaveButton.raise_()
        self.MainSettingsGBox.raise_()
        self.ServerSettingsGBox.raise_()
        self.InfoTextBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 26))
        self.menubar.setObjectName("menubar")
        self.FileMenu = QtWidgets.QMenu(self.menubar)
        self.FileMenu.setObjectName("FileMenu")
        self.SaveMenu = QtWidgets.QMenu(self.FileMenu)
        self.SaveMenu.setObjectName("SaveMenu")
        self.HelpMenu = QtWidgets.QMenu(self.menubar)
        self.HelpMenu.setObjectName("HelpMenu")
        self.WindowMenu = QtWidgets.QMenu(self.menubar)
        self.WindowMenu.setObjectName("WindowMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionWord = QtWidgets.QAction(MainWindow)
        self.actionWord.setObjectName("actionWord")
        self.ExcelAction = QtWidgets.QAction(MainWindow)
        self.ExcelAction.setObjectName("ExcelAction")
        self.SaveTxtAction = QtWidgets.QAction(MainWindow)
        self.SaveTxtAction.setObjectName("SaveTxtAction")
        self.AboutProgramAction = QtWidgets.QAction(MainWindow)
        self.AboutProgramAction.setObjectName("AboutProgramAction")
        self.AboutAuthorAction = QtWidgets.QAction(MainWindow)
        self.AboutAuthorAction.setObjectName("AboutAuthorAction")
        self.HelpAction = QtWidgets.QAction(MainWindow)
        self.HelpAction.setObjectName("HelpAction")
        self.ClearAction = QtWidgets.QAction(MainWindow)
        self.ClearAction.setObjectName("ClearAction")
        self.ExtiAction = QtWidgets.QAction(MainWindow)
        self.ExtiAction.setObjectName("ExtiAction")
        self.StartServerAction = QtWidgets.QAction(MainWindow)
        self.StartServerAction.setObjectName("StartServerAction")
        self.SaveMenu.addAction(self.SaveTxtAction)
        self.FileMenu.addAction(self.SaveMenu.menuAction())
        self.FileMenu.addAction(self.ExtiAction)
        self.HelpMenu.addAction(self.AboutProgramAction)
        self.HelpMenu.addAction(self.AboutAuthorAction)
        self.WindowMenu.addAction(self.ClearAction)
        self.menubar.addAction(self.FileMenu.menuAction())
        self.menubar.addAction(self.WindowMenu.menuAction())
        self.menubar.addAction(self.HelpMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NetMare"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP-Адрес"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Кол. запросов"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Длительность, с"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Время, мс"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Успешно"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Неуспешно"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Потери, %"))
        self.ClearButton.setText(_translate("MainWindow", "Очистить"))
        self.SaveButton.setText(_translate("MainWindow", "Сохранить лог"))
        self.WorkGBox.setTitle(_translate("MainWindow", "Метод работы:"))
        self.PingRButton.setText(_translate("MainWindow", "Пинг"))
        self.PortCheckerRButton.setText(_translate("MainWindow", "Проверка доступности порта"))
        self.DNSLookUpRButton.setText(_translate("MainWindow", "DNS LookUp"))
        self.GeoIPLookUpRButton.setText(_translate("MainWindow", "GeoIP LookUp"))
        self.DoButton.setText(_translate("MainWindow", "Выполнить"))
        self.NetworkLoadRButton.setText(_translate("MainWindow", "Проверка нагрузки"))
        self.MainSettingsGBox.setTitle(_translate("MainWindow", "Основные параметры:"))
        self.URILabel.setText(_translate("MainWindow", "URI-Адрес:"))
        self.PortLine.setInputMask(_translate("MainWindow", "00000"))
        self.PortLine.setText(_translate("MainWindow", "11208"))
        self.PortLabel.setText(_translate("MainWindow", "Порт:"))
        self.IpLabel.setText(_translate("MainWindow", "IP-Адрес:"))
        self.IpLine.setInputMask(_translate("MainWindow", "000.000.000.000;_"))
        self.IpLine.setText(_translate("MainWindow", "127.0.0.1"))
        self.CountLabel.setText(_translate("MainWindow", "Кол-во запросов:"))
        self.TimeoutLabel.setText(_translate("MainWindow", "Длительность (c):"))
        self.URILine.setText(_translate("MainWindow", "google.com"))
        self.TimeoutLine.setInputMask(_translate("MainWindow", "00.000"))
        self.TimeoutLine.setText(_translate("MainWindow", "5.000"))
        self.CountLine.setInputMask(_translate("MainWindow", "0000"))
        self.CountLine.setText(_translate("MainWindow", "4"))
        self.ServerSettingsGBox.setTitle(_translate("MainWindow", "Настройки подключения к серверу:"))
        self.Ip2Label.setText(_translate("MainWindow", "IP-Адрес:"))
        self.Ip2Line.setInputMask(_translate("MainWindow", "000.000.000.000;_"))
        self.Ip2Line.setText(_translate("MainWindow", "127.0.0.1"))
        self.Port2Label.setText(_translate("MainWindow", "Порт:"))
        self.Port2Line.setInputMask(_translate("MainWindow", "00000"))
        self.Port2Line.setText(_translate("MainWindow", "11208"))
        self.StartButton.setText(_translate("MainWindow", "Пуск"))
        self.label.setText(_translate("MainWindow", "Оффлайн"))
        self.onlinelabel.setText(_translate("MainWindow", "Оффлайн"))
        self.StopButton.setText(_translate("MainWindow", "Стоп"))
        self.InfoTextBox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.FileMenu.setTitle(_translate("MainWindow", "Файл"))
        self.SaveMenu.setTitle(_translate("MainWindow", "Сохранить"))
        self.HelpMenu.setTitle(_translate("MainWindow", "Помощь"))
        self.WindowMenu.setTitle(_translate("MainWindow", "Окно"))
        self.action.setText(_translate("MainWindow", "Открыть"))
        self.actionWord.setText(_translate("MainWindow", "Word"))
        self.ExcelAction.setText(_translate("MainWindow", "Excel"))
        self.SaveTxtAction.setText(_translate("MainWindow", "Txt"))
        self.AboutProgramAction.setText(_translate("MainWindow", "О программе"))
        self.AboutAuthorAction.setText(_translate("MainWindow", "Об авторе"))
        self.HelpAction.setText(_translate("MainWindow", "Справка"))
        self.ClearAction.setText(_translate("MainWindow", "Очистить"))
        self.ExtiAction.setText(_translate("MainWindow", "Выход"))
        self.StartServerAction.setText(_translate("MainWindow", "Запустить сервер"))
import Resources.resource_rc
